<?php

namespace superwave\migrate\commands;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;

class Make extends Command
{
    protected static     $defaultName        = 'make';
    protected static     $defaultDescription = '生成数据迁移脚本';
    protected Filesystem $filesystem;

    public function __construct(string $name = null)
    {
        parent::__construct($name);
        $this->filesystem = new Filesystem();
    }

    protected function configure()
    {
        $this->addArgument('db', InputArgument::REQUIRED, '运行的目标数据库');
        $this->addArgument('version', InputArgument::REQUIRED, '版本号');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $target_db = $input->getArgument('db');
        $path      = MIGRATION_DIR.DIRECTORY_SEPARATOR.$input->getArgument('version');
        if (!$this->filesystem->exists($path)) {
            $this->filesystem->mkdir($path);
        }
        $filename = sprintf('%s-%s-%d.sql', $target_db, $input->getArgument('version'), microtime(true) * 1000);
        $file     = $path.DIRECTORY_SEPARATOR.$filename;
        if (!$this->filesystem->exists($file)) {
            $this->filesystem->touch($file);
            $this->filesystem->appendToFile($file, '# Database migration sql file generated by command line'.PHP_EOL);
            $this->filesystem->appendToFile($file, '# datetime: '.date('Y-m-d H:i:s').PHP_EOL);
            $this->filesystem->appendToFile($file, '# filename: '.$filename.PHP_EOL);
            $this->filesystem->appendToFile($file, '# Database migration sql file generated by command line'.PHP_EOL);
            $output->writeln('生成迁移文件:'.$filename);
        } else {
            $output->writeln('存在相同的迁移文件:'.$filename);
        }
        return self::SUCCESS;
    }
}